### ISSUE TITLE
Reload hangs on Debian Wheezy 7.7 (HAProxyCTL 1.3.0)

### ISSUE THREAD

**Issue by aphorise** [flores/haproxyctl#20]
Its seems to reload fine as I get:
```sh
sudo haproxyctl reload
# gracefully stopping connections on pid 4557...
# ....
# CTRL+C
#  reloaded haproxy on pid
```
But it never goes beyond first line message. Is this a known issue?
I pulled from SID / did not make from source.

**Comment by flores** [comment]
Hi @aphorise 

This should only happen if there are connections still open on the listening ports of the running haproxy instance.  If there are no open connections it should reload immediately.  

However, it may also be an issue with the haproxy configuration file.  haproxyctl expects a `pidfile` line to a writable place (like `pidfile /var/run/haproxy.pid`) so it can track the running pid.

**Comment by aphorise** [comment]
@flores - I have ``pidfile`` defined in my HAProxy configuration file:
```
global
#.......
 stats socket    /tmp/haproxy.sock level admin
 pidfile /var/run/haproxy.pid
```
Which seems to be present & in use by main haproxy daemon:
```
ls -la /var/run/
  #...
   -rw-r--r--  1 root        root            5 Jan 27 14:13 haproxy.pid
```
If I do ``sudo haproxy restart #// or reload`` its rather fast without any issues or errors. Its only with ```sudo haproxyctl reload`` on an actively running instance where I get this - otherwise where there is none it does successfully start it.

Any other suggestion or have I've overlooked something obvious?

**Comment by flores** [comment]
For clarity, `restart` will terminate any existing connections then start a new haproxy instance immediately.   `reload` waits for any connections to close on the existing haproxy then brings up a new haproxy with the reloaded configuration.  I'm thinking this is a case where haproxy is currently serving requests or has connections open, so haproxyctl is just letting them complete.

One way to test if this is true is to try a `haproxyctl reload` on a box with no active connections.  It should look as fast as a restart.

**Comment by aphorise** [comment]
@flores is there any posability of trying this on Debian to concure or not?

I've experianced exactly the same behaviour on several Wheezy 7.7 versions using the stable release of HAProxy 1.5. 

I can confirm that the restart works as expected but not reload - furthermore this is only specific to Debian as on Ubuntu & CentOS both functions work as expected.

Many thanks for the support and guidance.

**Comment by flores** [comment]
@aphorise i am going to let this one sit as I stay away from computes in case someone watching this repo can test.  If they cannot, I will take a look.

**Comment by aphorise** [comment]
Issue specific to my host enviroments & setups.
I can confirm no subsequent issues on other Debian 7.8 install.
Thanks once again!.
