### ISSUE TITLE
Unable to down server ( permission denied ) 

### ISSUE THREAD

**Issue by johntdyer** [flores/haproxyctl#6]
Hello, I can seem to down servers, not sure why I am getting permission denied:

```
➜  bin git:(master) ✗ /etc/init.d/haproxyctl "disable server api_tropo/jboss2"
Permission denied
```

 I am running this as root, so I should have full access tot he socket file.  Other "read only" type commands work fine, its write actions that seem to be giving me issues... Any ideas?

**Comment by slmingol** [comment]
Ran into this exact issue:

```
$ echo "disable server bk_dservers/ds01" | nc -U /var/lib/haproxy/stats
Permission denied
```

Adding "level admin" to the stats in my configuration solved it.

**Comment by clavax-anand** [comment]
This is not working for me on HA-Proxy version 1.5.8 

 **#echo "disable server www_server1/web11" | socat stdio /var/run/haproxy/haproxy.sock**

It ran successfully but haproxy did not stop distributing load on web11 server. Health of web11 server is fluctuating.   

root@prelb2:~#  haproxyctl  "show health"  | grep "web11"
www_server1                     web11                          **MAINT**     1
checkout                       coweb11                        UP        1
root@prelb2:~#  haproxyctl  "show health"  | grep "web11"
www_server1                     web11                          **UP**        1
checkout                       coweb11                        UP        1
